fork = false
frame = "none"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
no-multigrid = false
srgb = true
tabs = false
title-hidden = true
vsync = true
wsl = false

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "native"

